### ISSUE TITLE
Er F-test forkert?

### ISSUE THREAD

**Issue by TobiasRoikjer** [paldepind/matmod#8]
I følge formlerne er 
```R
646 calcFTestsize <- function(s1, s2) {
647     s_max = max(s1, s2)
648     s_min = min(s1, s2)
649     F = s_max / s_min
650     eq(int("F = \\frac{ \\max( s^2_{(1)}, s^2_{(2)} ) }{ \\min( s^2_{(1)}, s^2_{(2)} ) } = `F`"))
651     return (F)
652 }
```
Men i bogen ((side 102)), er F altid `s_2^2/s_1^2`

**Comment by limemloh** [comment]
jeg har taget udgangspunkt i formlen på side 94 og slides fra uge 3
side 102 er et eksempel, så tænker at de springer over trinnet med max og min

**Comment by TobiasRoikjer** [comment]
Okay. Så det er *ikke* den rigtige formel for k > 2 samples. Det er to helt forskellige formler. s_1 vs s_(1)

**Comment by limemloh** [comment]
Jeg kan godt se at resultaterne ikke stemmer 
men det er vel selve pObs som er beregnet anderledes og ikke teststørrelsen

**Comment by TobiasRoikjer** [comment]
Jeg tror det er helt korrekt lavet, men jeg er i tvivl om navnet på den. For mig at se burde den hede ftest2samples, om ikke bare ftest.

**Comment by limemloh** [comment]
tak for at du pointerede det :smile:

**Comment by TobiasRoikjer** [comment]
Måske endda fTestSameMean2Samples :) Men jeg ved det ikke, om man kan lave andre ftest med 2 samples
